### ISSUE TITLE
Download war file gives an error

### ISSUE THREAD

**Issue by martinda** [jenkinsci/custom-distribution-service#123]
When I click "Download War File" when running with PR #105, I get a pop up saying:
```
localhost:3001 says:
This is something wrong with your configuration file.
Please fix and try again
```

The configuration file is:
```yaml
---
systemProperties:
  jenkins.install.runSetupWizard: "true"
  jenkins.model.Jenkins.slaveAgentPort: "5000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
casc:
  id: "casc"
  source:
    dir: "casc.yml"
plugins:
- groupId: "org.jenkins-ci.plugins"
  artifactId: "ccm"
  source:
    version: "3.2"
- groupId: "org.jenkins-ci.plugins"
  artifactId: "github-autostatus"
  source:
    version: "3.6.2"
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.107.3"
buildSettings:
  docker:
    build: "true"
    tag: ""
    base: ""
bundle:
  vendor: "Jenkins project"
  groupId: "io.jenkins.tools.custom-distribution-service.build"
  description: "123"
  artifactId: "ssd"
  title: "123"
```
