### ISSUE TITLE
War Generation is broken on master

### ISSUE THREAD

**Issue by sladyn98** [jenkinsci/custom-distribution-service#140]
```
app-server_1  | 2020-08-20 20:24:31.052 ERROR 1 --- [nio-8080-exec-1] c.o.j.c.j.d.service.PackagerController   : java.nio.file.NoSuchFileException: file:/app/custom-distribution-service-0.0.1.jar!/BOOT-INF/classes!/packager-config.yml
```
War generation seems to be broken on master because of incorrect mounting of volumes.

```
build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app'
```

@kwhetstone @martinda Cannot understand why this happens even though the correct volume is mounted
