### ISSUE TITLE
Docker in docker is not supported

### ISSUE THREAD

**Issue by martinda** [jenkinsci/custom-distribution-service#155]
When the configuration specification contains `build: "true"` like so:
```
buildSettings:
  docker:
    build: "true"
```

The war file generation fails with:
```
java.io.IOException: Cannot run program "docker" (in directory "tmp/output"): error=2, No such file or directory
```

**Comment by martinda** [comment]
Solution for now is to set the `build` to `false`:
```
buildSettings:
  docker:
    build: "false"
    tag: "tag1"
    base: "jenkins/jenkins:2.235.5-lts-jdk11"
```
